QuantumGoods/urls.py
from django.contrib import admin
from django.urls import path,include

# For showing media file
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include('Accounts.urls')),
    path("", include('Shop.urls')),
    path("order/", include('Order.urls')),
    path("payment/", include('Payment.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/urls.py
from django.urls import path
from .views import *

app_name = "Shop"

urlpatterns = [
    # path('',Home.as_view(),name='home'),
    path('',home,name='home'),
    path('all-products/',all_products,name='all_products'),
    # path('product/<slug:slug>/', ProductDetail.as_view(), name='product_detail'),
    path('product/<slug:slug>/', product_detail, name='product_detail'),
    
    
    # Product CRUD
    path('create-product/', createProduct, name='createProduct'),
    path('my-products/', product_list, name='product_list'),
    path('my-products/<int:pk>/update/', update_product, name='update_product'),
    path('my-products/<int:pk>/delete/', delete_product, name='delete_product'),
    
    # cupon
    path('coupon-create/', create_coupon, name='create_coupon'),
    path('coupon-list/', coupon_list, name='coupon_list'),
    path('coupon-update/<int:pk>/', update_coupon, name='update_coupon'),
    path('coupon-delete/<int:pk>/', delete_coupon, name='delete_coupon'),
    
    path('apply-coupon-products/<int:pk>/', apply_products_coupon, name='apply_products_coupon'),
    path('delete-applied-products/<int:pk>/', delete_products_coupon, name='delete_products_coupon'),
    
    #Category
    path('category-create/', create_category, name='create_category'),
    path('category-list/', all_category, name='all_category'),
    path('category-update/<int:pk>/', update_category, name='update_category'),
    path('category-delete/<int:pk>/', delete_category, name='delete_category'),
    
]

templates/coupon/apply_products_coupon.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container my-5">
    <h1>Apply Coupon to Product</h1>
    <form method="post">
        {% csrf_token %}
        <label for="coupon_code">Select Coupon:</label>
        <select id="coupon_code" class="form-select" name="coupon_code">
            {% for coupon in coupons %}
                <option value="{{ coupon.code }}">{{ coupon }}</option>
            {% endfor %}
        </select>
        <button class="btn btn-primary my-3" type="submit">Apply Coupon</button>
    </form>

</div>

{% endblock %}

templates/coupon/coupon_list.html
{% extends 'base.html' %}
{% block body_block %}

<div class="container my-5">
    <h1>Your Coupons</h1>
    <ul>
        {% for coupon in coupons %}
            <li>{{ coupon.code }} - {{ coupon.discount_percentage }}% - <a href="{% url 'Shop:update_coupon' coupon.pk %}">Edit</a> | <a href="{% url 'Shop:delete_coupon' coupon.pk %}">Delete</a></li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

templates/coupon/create_coupon.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container my-5">
    <h1>Create Coupon</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Create Coupon</button>
    </form>
</div>

{% endblock %}

templates/coupon/delete_coupon.html
{% extends 'base.html' %}
{% block body_block %}

<div class="container my-5">
    <h1>Delete Coupon</h1>
    <p>Are you sure you want to delete "{{ coupon.code }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">Confirm Delete</button>
    </form>
</div>

{% endblock %}

templates/coupon/update_coupon.html
{% extends 'base.html' %}
{% block body_block %}

<div class="container my-5">
    <h1>Update Coupon</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Update Coupon</button>
    </form>
</div>

{% endblock %}