Accounts/urls.py
from django.urls import path
from .views import *

app_name = "Accounts"

urlpatterns = [
    path('signup/', sign_up, name='signup'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('profile/', user_profile, name='profile'),
]

Order/urls.py
from django.urls import path
from .views import *

app_name = "Order"

urlpatterns = [
    path('add/<pk>/', add_to_cart, name="add"),
    path('cart/', cart_view, name="cart"),
    path('remove/<pk>/', remove_from_cart, name="remove_from_cart"),
    
    path('increase-item-quantity/<pk>/', increase_cart, name="increase_quantity"),
    path('decrease-item-quantity/<pk>/', decrease_cart, name="decrease_quantity"),
    
    path('see-all-purchesed/', see_all_purchesed_orders, name="see_all_purchesed_orders"),
    path('update-status/<pk>/', update_status, name="update_status"),
    

]

Payment/urls.py
from django.urls import path
from .views import *

app_name = 'Payment'

urlpatterns = [
     path('checkout/', checkout, name="checkout"),
     path('pay/', payment, name="payment"),
    path('status/', complete, name="complete"),
    path('purchase/<val_id>/<tran_id>/<payment_data>/', purchase, name="purchase"),
    path('orders/', order_view, name="orders"),
]

QuantumGoods/urls.py
from django.contrib import admin
from django.urls import path,include

# For showing media file
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include('Accounts.urls')),
    path("", include('Shop.urls')),
    path("order/", include('Order.urls')),
    path("payment/", include('Payment.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/urls.py
from django.urls import path
from .views import *

app_name = "Shop"

urlpatterns = [
    # path('',Home.as_view(),name='home'),
    path('',home,name='home'),
    path('all-products/',all_products,name='all_products'),
    # path('product/<slug:slug>/', ProductDetail.as_view(), name='product_detail'),
    path('product/<slug:slug>/', product_detail, name='product_detail'),
    
    
    # Product CRUD
    path('create-product/', createProduct, name='createProduct'),
    path('my-products/', product_list, name='product_list'),
    path('my-products/<int:pk>/update/', update_product, name='update_product'),
    path('my-products/<int:pk>/delete/', delete_product, name='delete_product'),
    
    # cupon
    path('coupon-create/', create_coupon, name='create_coupon'),
    path('coupon-list/', coupon_list, name='coupon_list'),
    path('coupon-update/<int:pk>/', update_coupon, name='update_coupon'),
    path('coupon-delete/<int:pk>/', delete_coupon, name='delete_coupon'),
    
    path('apply-coupon-products/<int:pk>/', apply_products_coupon, name='apply_products_coupon'),
    path('delete-applied-products/<int:pk>/', delete_products_coupon, name='delete_products_coupon'),
    
    #Category
    path('category-create/', create_category, name='create_category'),
    path('category-list/', all_category, name='all_category'),
    path('category-update/<int:pk>/', update_category, name='update_category'),
    path('category-delete/<int:pk>/', delete_category, name='delete_category'),
    
]

templates/includes/navbar.html
{% load cart_tag %}
<nav class="navbar navbar-expand-lg" style="background-color: #B6C4B6;">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'Shop:home' %}">QuantumGoods</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse ml-auto" id="navbarTogglerDemo02">
      <ul class="navbar-nav ms-auto ms-2 mb-2 mb-lg-0">
        {% if request.user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <img src="{{ request.user.profile.profile_picture.url }}" style="height: 35px;" alt="" />
              {% comment %} <i class="fas fa-user-tie"></i> {% endcomment %}
            </a>
            <ul class="dropdown-menu">
              <li>
                <a class="dropdown-item" href="{% url 'Accounts:profile' %}">Profile</a>
              </li>

              {% if request.user.user_type == 'seller' %}
                <li>
                  <a class="dropdown-item" href="{% url 'Shop:createProduct' %}">Create Product</a>
                </li>
                <li>
                  <a class="dropdown-item" href="{% url 'Shop:product_list' %}">My Product</a>
                </li>
                <li>
                  <a class="dropdown-item" href="{% url 'Shop:create_coupon' %}">Create Cupon</a>
                </li>
                <li>
                  <a class="dropdown-item" href="{% url 'Shop:coupon_list' %}">My Cupon</a>
                </li>
                <li>
                  <a class="dropdown-item" href="{% url 'Shop:all_category' %}">All my category</a>
                </li>
                <li>
                  <a class="dropdown-item" href="{% url 'Shop:create_category' %}">Create category</a>
                </li>
                <li>
                  <a class="dropdown-item" href="{% url 'Order:see_all_purchesed_orders' %}">See all products order</a>
                </li>
              {% else %}
                <li>
                  <a class="dropdown-item" href="{% url 'Payment:orders' %}">Orders</a>
                </li>
              {% endif %}

              <li>
                <a class="dropdown-item" href="{% url 'Accounts:logout' %}">Logout</a>
              </li>
            </ul>
          </li>

          {% if request.user.user_type == 'buyer' %}
            <li class="nav-item">
              <a href="{% url 'Order:cart' %}" class="nav-link">
                <i class="fa fa-shopping-cart"></i> Cart
                <span class="badge badge-light">{{ cart_count }}</span>
              </a>
            </li>
          {% endif %}
        {% else %}
          <li class="nav-item">
            <a href="{% url 'Accounts:login' %}" class="btn btn-primary">Login</a>
            <a href="{% url 'Accounts:signup' %}" class="btn btn-primary">Signup</a>
          </li>
        {% endif %}
        <li class="nav-item">
          <a href="{% url 'Shop:all_products' %}" class="nav-link">Store</a>
        </li>
      <li class="nav-item d-flex align-items-center">
        <form action="{% url 'Shop:all_products' %}" method="get" class="d-flex">
          <input class="form-control form-control-sm me-2" name="search" type="text" placeholder="Search product" aria-label=".form-control-sm example" />
          <button type="submit" class="btn btn-success btn-sm">Search</button>
        </form>
      </li>

      </ul>
    </div>
  </div>
</nav>