Order/urls.py
from django.urls import path
from .views import *

app_name = "Order"

urlpatterns = [
    path('add/<pk>/', add_to_cart, name="add"),
    path('cart/', cart_view, name="cart"),
    path('remove/<pk>/', remove_from_cart, name="remove_from_cart"),
    
    path('increase-item-quantity/<pk>/', increase_cart, name="increase_quantity"),
    path('decrease-item-quantity/<pk>/', decrease_cart, name="decrease_quantity"),
    
    path('see-all-purchesed/', see_all_purchesed_orders, name="see_all_purchesed_orders"),
    path('update-status/<pk>/', update_status, name="update_status"),
    

]

QuantumGoods/urls.py
from django.contrib import admin
from django.urls import path,include

# For showing media file
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include('Accounts.urls')),
    path("", include('Shop.urls')),
    path("order/", include('Order.urls')),
    path("payment/", include('Payment.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/urls.py
from django.urls import path
from .views import *

app_name = "Shop"

urlpatterns = [
    # path('',Home.as_view(),name='home'),
    path('',home,name='home'),
    path('all-products/',all_products,name='all_products'),
    # path('product/<slug:slug>/', ProductDetail.as_view(), name='product_detail'),
    path('product/<slug:slug>/', product_detail, name='product_detail'),
    
    
    # Product CRUD
    path('create-product/', createProduct, name='createProduct'),
    path('my-products/', product_list, name='product_list'),
    path('my-products/<int:pk>/update/', update_product, name='update_product'),
    path('my-products/<int:pk>/delete/', delete_product, name='delete_product'),
    
    # cupon
    path('coupon-create/', create_coupon, name='create_coupon'),
    path('coupon-list/', coupon_list, name='coupon_list'),
    path('coupon-update/<int:pk>/', update_coupon, name='update_coupon'),
    path('coupon-delete/<int:pk>/', delete_coupon, name='delete_coupon'),
    
    path('apply-coupon-products/<int:pk>/', apply_products_coupon, name='apply_products_coupon'),
    path('delete-applied-products/<int:pk>/', delete_products_coupon, name='delete_products_coupon'),
    
    #Category
    path('category-create/', create_category, name='create_category'),
    path('category-list/', all_category, name='all_category'),
    path('category-update/<int:pk>/', update_category, name='update_category'),
    path('category-delete/<int:pk>/', delete_category, name='delete_category'),
    
]

Shop/forms.py
from django import forms
from .models import *


class ProductForm(forms.ModelForm):
    
    class Meta:
        model = Product
        fields = ('product_name','description','price','old_price','images','stock','category',)
        # fields = '__all__'
        
        
    def __init__(self, *args, **kwargs):
          super(ProductForm, self).__init__(*args, **kwargs)
          for field in self.fields:
               self.fields[field].widget.attrs['class'] = 'form-control'
               
class CouponForm(forms.ModelForm):
    class Meta:
        model = Coupon
        fields = ['code', 'discount_percentage']
        
    def __init__(self, *args, **kwargs):
          super(CouponForm, self).__init__(*args, **kwargs)
          for field in self.fields:
               self.fields[field].widget.attrs['class'] = 'form-control'
class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['category_name','description', ]
        
    def __init__(self, *args, **kwargs):
          super(CategoryForm, self).__init__(*args, **kwargs)
          for field in self.fields:
               self.fields[field].widget.attrs['class'] = 'form-control'

Shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import *
from django.utils.text import slugify
from django.core.exceptions import PermissionDenied
from django.contrib import messages

# Import views
from django.views.generic import ListView, DetailView

# Models
from .models import Product
from Order.models import Cart,Order
# Mixin
from django.contrib.auth.mixins import LoginRequiredMixin

class Home(ListView):
    model = Product
    context_object_name = 'products'
    template_name='Shop/home.html'
    
    
def home(request):
    products = Product.objects.filter(featured_product=True)
    context = {
        'products':products,
    }
    return render(request,'Shop/home.html',context=context)



def all_products(request):
    query = request.GET.get('search')
    if query:
        products = Product.objects.filter(product_name__icontains=query).order_by('-id')
    else:
        products = Product.objects.all().order_by('-id')
    
    paginator = Paginator(products, 2)  
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
        
    context = {
        'products': products,
        'query': query,
    }
    return render(request, 'Shop/all-products.html', context=context)

class ProductDetail(LoginRequiredMixin,DetailView):
    model = Product
    context_object_name = 'product'
    slug_field = 'slug'
    template_name='Shop/product_detail.html'


@login_required
def product_detail(request,slug):
    product = Product.objects.get(slug=slug)
    
    if Cart.objects.filter( user= request.user,item = product,purchased = False).exists():
        cart = True
    else:
        cart = False
    context = {
        'product':product,
        'cart':cart
    }
    return render(request,'Shop/product_detail.html',context=context)


@login_required
def createProduct(request):
    form = ProductForm(request.POST, request.FILES or None)
    if request.user.user_type == "seller":
    
        if request.method == 'POST':
            if form.is_valid():
                product = form.save(commit=False)
                # Automatically generate slug from product name
                product.slug = slugify(product.product_name)
                product.product_user = request.user
                product.save()
                return redirect('Shop:home')
        else:
            form = ProductForm()
    else:
        messages.info(request, f"You are not allowed")
        return redirect('Shop:home')
    context = {
        'form': form
    }
    return render(request, 'Shop/create-product.html', context=context)

@login_required
def product_list(request):
    if request.user.user_type == "seller":
        products = Product.objects.filter(product_user = request.user)
    else:
        messages.info(request, f"You are not allowed")
        return redirect('Shop:home')
    return render(request, 'Shop/product_list.html', {'products': products})

@login_required
def update_product(request, pk):
    if request.user.user_type == "seller":
        product = get_object_or_404(Product, pk=pk)
        if product.product_user == request.user:
            form = ProductForm(request.POST or None, request.FILES or None, instance=product)
            if form.is_valid():
                form.save()
                return redirect('Shop:product_list')
        else:
                return redirect('Shop:home')
        
    else:
        messages.info(request, f"You are not allowed")
        return redirect('Shop:home')

        
    return render(request, 'Shop/create-product.html', {'form': form})

@login_required
def delete_product(request, pk):
    if request.user.user_type == "seller":
        product = get_object_or_404(Product, pk=pk)
        if product.product_user == request.user:
        
            if request.method == 'POST':
                product.delete()
                return redirect('Shop:product_list')
        else:
                return redirect('Shop:home')
    else:
        messages.info(request, f"You are not allowed")
        return redirect('Shop:home')
    return render(request, 'Shop/product_confirm_delete.html', {'product': product})



# cupon
@login_required
def create_coupon(request):
    if request.user.user_type == "seller":
        
        if request.method == 'POST':
            form = CouponForm(request.POST)
            if form.is_valid():
                coupon = form.save(commit=False)
                coupon.cupon_user = request.user
                coupon.save()
                return redirect('Shop:coupon_list')
        else:
            form = CouponForm()
    else:
        messages.info(request, f"You are not allowed")
        return redirect('Shop:home')

    return render(request, 'coupon/create_coupon.html', {'form': form})

@login_required
def coupon_list(request):
    if request.user.user_type == "seller":
        coupons = Coupon.objects.filter(cupon_user=request.user)
    else:
        messages.info(request, f"You are not allowed")
        return redirect('Shop:home')
    return render(request, 'coupon/coupon_list.html', {'coupons': coupons})

@login_required
def update_coupon(request, pk):
    if request.user.user_type == "seller":
        
        coupon = get_object_or_404(Coupon, pk=pk)
        if coupon.cupon_user != request.user:
            raise PermissionDenied
        if request.method == 'POST':
            form = CouponForm(request.POST, instance=coupon)
            if form.is_valid():
                form.save()
                return redirect('Shop:coupon_list')
        else:
            form = CouponForm(instance=coupon)
    else:
        messages.info(request, f"You are not allowed")
        return redirect('Shop:home')

    return render(request, 'coupon/update_coupon.html', {'form': form})

@login_required
def delete_coupon(request, pk):
    if request.user.user_type == "seller":

        coupon = get_object_or_404(Coupon, pk=pk)
        if coupon.cupon_user != request.user:
            raise PermissionDenied
        if request.method == 'POST':
            coupon.delete()
            return redirect('Shop:coupon_list')

    else:
        messages.info(request, f"You are not allowed")
        return redirect('Shop:home')
    return render(request, 'coupon/delete_coupon.html', {'coupon': coupon})


@login_required
def apply_products_coupon(request, pk):
    if request.user.user_type == "seller":

        product = get_object_or_404(Product, id=pk)
        coupons = Coupon.objects.filter(cupon_user=request.user)
        if request.method == 'POST':
            coupon_code = request.POST.get('coupon_code')
            try:
                coupon = Coupon.objects.get(code=coupon_code)
                if coupon in coupons:
                    product.coupon_code = coupon
                    product.save()
                    messages.info(request, f"Coupon added for the products")
                    return redirect('Shop:product_list')
                else:
                    messages.error(request, f"Coupon was not added for the products")
                    return redirect('Shop:product_list')
                    # Coupon does not belong to the current user
            except Coupon.DoesNotExist:
                return redirect('Shop:product_list')

    else:
        messages.info(request, f"You are not allowed")
        return redirect('Shop:home')
    

    return render(request, 'coupon/apply_products_coupon.html', {'coupons': coupons, 'product': product})


@login_required
def delete_products_coupon(request,pk):
    
    if request.user.user_type == "seller":
        try:
            
            product = get_object_or_404(Product, id=pk)
            if product:
                product.coupon_code = None
                product.save()
                messages.info(request, f"Coupon deleted for the products")
                return redirect('Shop:product_list')
                
        except:
                messages.info(request, f"You are not allowed")
                return redirect('Shop:product_list')
    
    else:
        messages.info(request, f"You are not allowed")
        return redirect('Shop:home')
            
            
        
@login_required
def create_category(request):
    form = CategoryForm(request.POST or None)
    if request.user.user_type == "seller":

        if request.method =="POST":
            if form.is_valid():
                form = form.save(commit=False)
                form.user = request.user 
                form.save()
                return redirect('Shop:all_category')
            
    else:
        messages.info(request, f"You are not allowed")
        return redirect('Shop:home')
        
        
    context = {
        'form':form
    }
    return render(request, 'Shop/category/form.html',context )
        
@login_required
def all_category(request):
    category = None
    if request.user.user_type == "seller":
        category = Category.objects.filter(user=request.user)            
    else:
        messages.info(request, f"You are not allowed")
        return redirect('Shop:home')
        
        
    context = {
        'category':category
    }
    return render(request, 'Shop/category/all-category.html',context )
        
@login_required
def update_category(request,pk):
    category = Category.objects.get(id = pk)
    form = CategoryForm(request.POST or None,instance = category)
    if request.user.user_type == "seller":

        if request.method =="POST":
            if form.is_valid():
                form = form.save(commit=False)
                form.save()
                return redirect('Shop:all_category')
            
            

templates/Shop/all-products.html
{% extends 'base.html' %}
{% block body_block %}
  <div class="container my-5">
    <h2 class="my-5">All Products</h2>

    <div class="row">
      {% if products %}
        {% for product in products %}
          <div class="col-md-4 mb-4">
            <div class="card" style="width: 18rem;">
              <a href="{% url 'Shop:product_detail' slug=product.slug %}"><img src="{{ product.images.url }}" style="width: 100%; height: 15rem;" class="card-img-top" alt="{{ product.description }}" /></a>
              <div class="card-body">
                <h5 class="card-title"><a href="{% url 'Shop:product_detail' slug=product.slug %}">{{ product.product_name }}</a></h5>
                <span>Old Price: <strike>{{ product.old_price }}</strike></span>
                <p>Price: {{ product.price }}</p>
              </div>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <p>No products found.</p>
      {% endif %}
    </div>

    <div class="mt-3 p-1 container">
      <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
          {% if products.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page=1{% if query %}{{ query }}{% endif %}">First</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="?page={{ products.previous_page_number }}{% if query %}{{ query }}{% endif %}">Previous</a>
            </li>
          {% endif %}
          <li class="page-item disabled">
            <span class="page-link">Page {{ products.number }} of {{ products.paginator.num_pages }}</span>
          </li>
          {% if products.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ products.next_page_number }}{% if query %}{{ query }}{% endif %}">Next</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="?page={{ products.paginator.num_pages }}{% if query %}{{ query }}{% endif %}">Last</a>
            </li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </div>
{% endblock %}

templates/Shop/create-product.html
{% extends 'base.html' %}
{% block body_block %}

<div class="container mt-4">
     <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {{form}}
          <input class="btn btn-primary my-3" type="submit" value="Create product">
     </form>
</div>

{% endblock %}

templates/Shop/home.html
{% extends 'base.html' %}
{% block body_block %}
<img class="full-width-banner" src="https://raw.githubusercontent.com/MdAshiqurRahmanZayed/DjangoEcommerce/main/static/images/banners/cover.jpg" alt="" srcset="">

<div class="container my-5">
  <h2 class="my-5">Featured Products</h2>
  <div class="row">
    {% for product in products %}
    <div class="col">
      <div class="card" style="width: 19rem;">
        <img src="{{product.images.url}}" style="width: 18rem;height: 15rem;" class="card-img-top" alt="{{product.description}}">
        <div class="card-body">
          <h5 class="card-title">
          <a href="{% url 'Shop:product_detail' slug=product.slug %}">
            {{product.product_name}}
          </a>
          </h5>
          <span >Old Price: <strike>{{product.old_price}}</strike></span>
          <p >Price:{{product.price}}</p>
        </div>
      </div>

    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

templates/Shop/product_confirm_delete.html
{% extends 'base.html' %}
{% block body_block %}

<div class="container mt-4">
    <h1>Confirm Deletion</h1>
    <p>Are you sure you want to delete "{{ product.product_name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">Confirm</button>
    </form>
</div>

{% endblock %}

templates/Shop/product_detail.html
{% extends 'base.html' %}
{% block body_block %}

<div class="container mt-4">
     <div class="row">
          <div class="col-md-6">
               <img src="{{ product.images.url }}" alt="{{ product.product_name }}" class="img-fluid">
          </div>
          <div class="col-md-6">
               <h2>{{ product.product_name }}</h2>
               <p class="text-muted">Category: {{ product.category }}</p>
               <p>{{ product.description }}</p>
               <p>Price: ${{ product.price }}</p>
               {% if product.price %}
               <p>Old Price: ${{ product.old_price }}</p>
               {% endif %}
               {% if product.coupon_code %}
               <p>Coupon Code: {{ product.coupon_code.code }}</p>
               {% endif %}
               <p>Stock: {{ product.stock }}</p>
               <p>Status:
                    {% if product.stock >= 1 %}
                    <span class="text-success">Available</span>
                    {% else %}
                    <span class="text-danger">Out of Stock</span>
                    {% endif %}
               </p>


               {% if product.stock >= 1 %}
               {% if not cart %}
               {% if request.user.user_type == "buyer" %}
               <a href="{% url 'Order:add' pk=product.id %}" class="btn btn-primary">Add to Cart</a>
               {% else %}
               <p>Login as buyer</p>
               {% endif %}
                    
               {% else %}
               <p>Already added to <b>Cart</b></p>
               {% endif %}
               {% else %}
               {% endif %}

               {% comment %} <a href="{% url 'Order:add' pk=product.id %}" class="btn btn-primary">Add to Cart</a> {% endcomment %}


          </div>
     </div>
</div>

{% endblock %}

templates/Shop/product_list.html
{% extends 'base.html' %}

{% block body_block %}

<div class="container mt-4">
    <h1>My Product List</h1>
    <ul>
        {% for product in products %}
            <li>
                {{ product.product_name }} - 
                <a href="{% url 'Shop:update_product' product.pk %}">Edit</a> | 
                <a href="{% url 'Shop:delete_product' product.pk %}">Delete</a> | 
                <a href="{% url 'Shop:apply_products_coupon' product.pk %}">Apply Coupon</a>
                {% if product.coupon_code %}
                    - <b>Coupon Applied:</b> {{ product.coupon_code }} - 
                    
                <a href="{% url 'Shop:delete_products_coupon' product.pk %}">
                    <div class="btn btn-sm btn-danger">Delete coupon</div>
                </a>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}