Order/urls.py
from django.urls import path
from .views import *

app_name = "Order"

urlpatterns = [
    path('add/<pk>/', add_to_cart, name="add"),
    path('cart/', cart_view, name="cart"),
    path('remove/<pk>/', remove_from_cart, name="remove_from_cart"),
    
    path('increase-item-quantity/<pk>/', increase_cart, name="increase_quantity"),
    path('decrease-item-quantity/<pk>/', decrease_cart, name="decrease_quantity"),
    
    path('see-all-purchesed/', see_all_purchesed_orders, name="see_all_purchesed_orders"),
    path('update-status/<pk>/', update_status, name="update_status"),
    

]

Payment/urls.py
from django.urls import path
from .views import *

app_name = 'Payment'

urlpatterns = [
     path('checkout/', checkout, name="checkout"),
     path('pay/', payment, name="payment"),
    path('status/', complete, name="complete"),
    path('purchase/<val_id>/<tran_id>/<payment_data>/', purchase, name="purchase"),
    path('orders/', order_view, name="orders"),
]

QuantumGoods/urls.py
from django.contrib import admin
from django.urls import path,include

# For showing media file
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include('Accounts.urls')),
    path("", include('Shop.urls')),
    path("order/", include('Order.urls')),
    path("payment/", include('Payment.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/urls.py
from django.urls import path
from .views import *

app_name = "Shop"

urlpatterns = [
    # path('',Home.as_view(),name='home'),
    path('',home,name='home'),
    path('all-products/',all_products,name='all_products'),
    # path('product/<slug:slug>/', ProductDetail.as_view(), name='product_detail'),
    path('product/<slug:slug>/', product_detail, name='product_detail'),
    
    
    # Product CRUD
    path('create-product/', createProduct, name='createProduct'),
    path('my-products/', product_list, name='product_list'),
    path('my-products/<int:pk>/update/', update_product, name='update_product'),
    path('my-products/<int:pk>/delete/', delete_product, name='delete_product'),
    
    # cupon
    path('coupon-create/', create_coupon, name='create_coupon'),
    path('coupon-list/', coupon_list, name='coupon_list'),
    path('coupon-update/<int:pk>/', update_coupon, name='update_coupon'),
    path('coupon-delete/<int:pk>/', delete_coupon, name='delete_coupon'),
    
    path('apply-coupon-products/<int:pk>/', apply_products_coupon, name='apply_products_coupon'),
    path('delete-applied-products/<int:pk>/', delete_products_coupon, name='delete_products_coupon'),
    
    #Category
    path('category-create/', create_category, name='create_category'),
    path('category-list/', all_category, name='all_category'),
    path('category-update/<int:pk>/', update_category, name='update_category'),
    path('category-delete/<int:pk>/', delete_category, name='delete_category'),
    
]

Order/models.py
from django.db import models
from django.conf import settings

# Model
from Shop.models import Product
# Create your models here.
class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="cart")
    item = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="cart_product_name")
    quantity = models.IntegerField(default=1)
    purchased = models.BooleanField(default=False)
    coupon_applied = models.BooleanField(default=False)  
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.quantity} X {self.item}'

    def get_total(self):
        if self.coupon_applied  == False:
            total = self.item.price * self.quantity
            float_total = format(total, '0.2f')
            return float_total
        else:
            # print(self.item.coupon_code.discount_percentage)
            # discount = (100 - int(self.item.coupon_code.discount_percentage)) / 100  
            # print(discount)
            total = (100- self.item.coupon_code.discount_percentage)/100 * self.item.price * self.quantity   
            # print((100- self.item.coupon_code.discount_percentage)/100 * self.item.price * self.quantity )
            float_total = format(total, '0.2f')
            return float_total

ORDER_STATUS_CHOICES = {
    'PENDING': 'Pending',
    'PROCESSING': 'Processing',
    'SHIPPED': 'Shipped',
    'DELIVERED': 'Delivered',
    'CANCELLED': 'Cancelled'
}
class Order(models.Model):
    orderitems = models.ManyToManyField(Cart)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    paymentId = models.CharField(max_length=264, blank=True, null=True)
    orderId = models.CharField(max_length=200, blank=True, null=True)
    full_payment_data  = models.TextField( blank=True, null=True)
    order_status = models.CharField(max_length=20, choices=ORDER_STATUS_CHOICES, default='PENDING')

    def get_totals(self):
        total = 0
        for order_item in self.orderitems.all():
            total += float(order_item.get_total())
        return total
   
    def __str__(self):
        return f'{self.user}'

Order/forms.py
from django import forms
from .models import *


class OrderStatusForm(forms.ModelForm):
    order_status = forms.ChoiceField(
        choices=ORDER_STATUS_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    class Meta:
        model = Order
        fields = ('order_status',)

Order/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import *
# Authentications
from django.contrib.auth.decorators import login_required

# Model
from Order.models import Cart, Order
from Shop.models import Product,Coupon
# Messages
from django.contrib import messages


@login_required
def add_to_cart(request, pk):
    if request.user.user_type == "buyer":
        
        item = get_object_or_404(Product, pk=pk)

        order_item = Cart.objects.get_or_create(item=item, user=request.user, purchased=False)

        order_qs = Order.objects.filter(user=request.user, ordered=False)

        if order_qs.exists():
            order = order_qs[0]

            if order.orderitems.filter(item=item).exists():
                order_item[0].quantity += 1
                order_item[0].save()
                item.stock -= 1
                item.save()
                messages.info(request, f"{item.product_name} item quantity was updated.")
                return redirect("Shop:home")
            else:
                order.orderitems.add(order_item[0])
                item.stock -= 1
                item.save()
                messages.info(request, f"{item.product_name} item was added to your cart.")
                return redirect("Shop:home")
        else:
            order = Order(user=request.user)
            order.save()
            item.stock -= 1
            item.save()

            order.orderitems.add(order_item[0])
            messages.info(request, f"{item.product_name} item was added to your cart.")
            return redirect("Shop:home")
    else:
        messages.info(request, f"You are not allowed")
        return redirect('Shop:home')
    
@login_required
def cart_view(request):
    if request.user.user_type == "buyer":
        # print(request.user.user_type == "buyer")
        carts = Cart.objects.filter(user =request.user,purchased = False)
        orders = Order.objects.filter(user =request.user,ordered= False)
        # print(carts)
        if carts.exists() and orders.exists():
            order = orders[0]
            if request.method =='POST':
                coupon_code = request.POST.get('coupon_code')
                pk = request.POST.get('product')
                product = Product.objects.get(id = pk)
                print(coupon_code)
                try:
                    coupon = Coupon.objects.get(code=coupon_code)
                    cart = Cart.objects.filter(item = product ,item__coupon_code=coupon,coupon_applied=False)
           
                    print(cart)
                    if cart:
                        if cart[0].coupon_applied == False:
                            for i in range(len(cart)):
                                cart[i].coupon_applied = True
                                cart[i].save()
                except Coupon.DoesNotExist:
                    messages.info(request, "Invalid coupon code!")
            context = {
                'carts':carts,
                'order':order,
            }
            return render(request,'Order/cart.html',context=context)
        else:
            messages.warning(request, "You don't have any item in your cart!")
            return redirect("Shop:home")
    else:
        messages.info(request, f"You are not allowed")
        return redirect('Shop:home')



@login_required
def remove_from_cart(request, pk):
    if request.user.user_type == "buyer":
        
        item = get_object_or_404(Product, pk=pk)
        order_qs = Order.objects.filter(user=request.user, ordered=False)
        if order_qs.exists():
            order = order_qs[0]
            if order.orderitems.filter(item=item).exists():
                order_item = Cart.objects.filter(item=item, user=request.user, purchased=False)[0]
                order.orderitems.remove(order_item)
                item.stock += order_item.quantity
                item.save()
                order_item.delete()
                messages.warning(request, f"{item.product_name} item was removed form your cart")
                return redirect("Order:cart")
            else:
                messages.info(request, f"{item.product_name} item was not in your cart.")
                return redirect("Shop:home")
        else:
            messages.info(request, "You don't have an active order")
            return redirect("Shop:home")
    else:
        messages.info(request, f"You are not allowed")
        return redirect('Shop:home')
    
    
@login_required
def increase_cart(request, pk):
    
    if request.user.user_type == "buyer":
        
        item = get_object_or_404(Product, pk=pk)
        order_qs = Order.objects.filter(user=request.user, ordered=False)
        if order_qs.exists():
            order = order_qs[0]
            if order.orderitems.filter(item=item).exists():
                order_item = Cart.objects.filter(item=item, user=request.user, purchased=False)[0]
                if order_item.quantity >= 1:
                    order_item.quantity += 1
                    order_item.save()
                    item.stock -= 1
                    item.save()
                    messages.info(request, f"{item.product_name} quantity has been updated")
                    return redirect("Order:cart")
            else:
                messages.info(request, f"{item.product_name} is not in your cart")
                return redirect("Shop:home")
        else:
            messages.info(request, "You don't have an active order")
            return redirect("Shop:home")
    else:
        messages.info(request, f"You are not allowed")
        return redirect('Shop:home')
    


@login_required
def decrease_cart(request, pk):
    if request.user.user_type == "buyer":
        
        item = get_object_or_404(Product, pk=pk)
        order_qs = Order.objects.filter(user=request.user, ordered=False)
        if order_qs.exists():
            order = order_qs[0]
            if order.orderitems.filter(item=item).exists():
                order_item = Cart.objects.filter(item=item, user=request.user, purchased=False)[0]
                if order_item.quantity > 1:
                    order_item.quantity -= 1
                    order_item.save()
                    item.stock += 1
                    item.save()
                    messages.info(request, f"{item.product_name} quantity has been updated")
                    return redirect("Order:cart")
                else:
                    order.orderitems.remove(order_item)
                    order_item.delete()
                    messages.warning(request, f"{item.product_name} item has been removed from your cart")
                    return redirect("Order:cart")
            else:
                messages.info(request, f"{item.product_name} is not in your cart")
                return redirect("Shop:home")
        else:
            messages.info(request, "You don't have an active order")
            return redirect("Shop:home")
    else:
        messages.info(request, f"You are not allowed")
        return redirect('Shop:home')


@login_required
def see_all_purchesed_orders(request,pk=None):
    if request.user.user_type == "seller":
    
        form = OrderStatusForm(request.POST or None)
        all_orders = Order.objects.filter(orderitems__item__product_user=request.user)

        context ={
            'all_orders':all_orders,
            'form':form
        }
        return render(request, 'Order/all-orders.html',context )
    
    else:
        messages.info(request, f"You are not allowed")
        return redirect('Shop:home')
    
@login_required    
def update_status(request, pk):
    order = get_object_or_404(Order, id=pk)
    order_form = OrderStatusForm(instance=order)
    if request.user.user_type == "seller":
        if request.method == "POST":
            order_form = OrderStatusForm(request.POST,instance=order)
            if order_form.is_valid():
                order_form.save()
                messages.success(request, "Order status updated successfully.")
                return redirect('Order:see_all_purchesed_orders') 
            else:
                messages.error(request, "Failed to update order status. Please correct the errors.")
        else:
            return redirect('Order:see_all_purchased_orders')  
    else:
        messages.info(request, "You are not allowed.")
        return redirect('Shop:home')  

templates/Order/all-orders.html
{% extends 'base.html' %}
{% block body_block %}
  <div class="container my-5">
    <div class="my-5">
      <h2>Your Cart</h2>
    </div>
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col" width="15%">#</th>
            <th scope="col">Order Items</th>
            <th scope="col">Created</th>
            <th scope="col" align="right">Payment Id</th>
            <th scope="col">Order Id</th>
            <th scope="col" width="20%">Order Status</th>
          </tr>
        </thead>
        <tbody>
          {% for order in all_orders %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <td>
                {% for item in order.orderitems.all %}
                  {{ item }}<br />
                {% endfor %}
              </td>
              <td>{{ order.created }}</td>
              <td align="right">{{ order.paymentId }}</td>
              <td>{{ order.orderId }}</td>
              <td class="w-75">
                <p class="text-info">{{ order.order_status }}</p>
                <form action="{% url 'Order:update_status' order.id %}" method="post">
                  {% csrf_token %}
                  {{ form.order_status }}
                  <button type="submit" class="btn btn-primary mt-2">Change Status</button>
                </form>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

templates/Order/cart.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container my-5">
     <div class="my-5">
          <h2>Your Cart</h2>
     </div>
     <table class="table table-hover">
          <thead>
               <tr>
                    <th scope="col" width="15%">#</th>
                    <th scope="col">Product Name</th>
                    <th scope="col">Quantity</th>
                    <th scope="col" align="right">Price</th>
                    <th scop="col">Remove</th>
                    <th scop="col">Apply</th>
               </tr>
          </thead>
          <tbody>
               {% for cart in carts %}
               <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{cart.item.product_name}}</td>
                    <td>
                         <a class="mr-2" href="{% url 'Order:decrease_quantity' cart.item.pk %}">
                              <span class="badge rounded-pill bg-secondary"><i class="fas fa-minus"></i></span>
                         </a>
                         {{ cart.quantity }}
                         <a class="mr-2" href="{% url 'Order:increase_quantity' cart.item.pk %}"> 
                              <span class="badge rounded-pill bg-secondary"> <i class="fas fa-plus"></i></span>
                         </a>
                    </td>
                    <td align="right">&#2547; {{cart.get_total}}</td>
                    <td><a href="{% url 'Order:remove_from_cart' pk=cart.item.pk %}" class="btn btn-danger btn-sm">Remove From Cart</a></td>
                    <td>
                         <form  method="POST">
                              {% csrf_token %}
                              <input class="form-control" name="coupon_code" type="text" placeholder="Coupon code" >
                              <input name="product" type="hidden" value="{{cart.item.id}}">
                              <input class="btn btn-primary my-1" type="submit" value="Apply">
                         </form>
                    </td>
               </tr>
               {% endfor %}
               <tr>
                    <th scope="row"></th>
                    <td colspan="2">Total</td>
                    <td align="right">&#2547; {{order.get_totals | floatformat:2 }}</td>
                    <td></td>
               </tr>
               <tr>
                    <th scope="row"></th>
                    <td colspan="4" class="text-right">
                         <a href="{% url 'Shop:home' %}" class="btn btn-warning mr-4">Continue Shoping</a>
                         <a href="{% url 'Payment:checkout' %}" class="btn btn-success mr-4">Proceed To Checkout</a>
                    </td>
               </tr>
          </tbody>
     </table>
</div>
{% endblock %}